# -- 코드를 입력하세요

SELECT 
    E.AUTHOR_ID, E.AUTHOR_NAME, E.CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM(
SELECT 
    A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY,
    (A.PRICE * D.TOTAL) AS TOTAL_SALES
FROM BOOK A
    JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL
    FROM BOOK_SALES
    WHERE MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
    ) D ON D.BOOK_ID = A.BOOK_ID
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.BOOK_ID
) E
GROUP BY E.AUTHOR_ID, E.AUTHOR_NAME, E.CATEGORY
ORDER BY E.AUTHOR_ID, E.CATEGORY DESC
;



# SELECT 
#     A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY,
#     A.PRICE, D.TOTAL
# FROM BOOK A
#     JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
#     JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL
#     FROM BOOK_SALES
#     GROUP BY BOOK_ID) D ON D.BOOK_ID = A.BOOK_ID
# ;


# SELECT *
# FROM BOOK_SALES
# WHERE MONTH(SALES_DATE) = 1;
# # GROUP BY BOOK_ID;

