-- 코드를 입력하세요

SELECT
    A.CART_ID
FROM(
SELECT *, 
    CASE WHEN NAME = 'Milk' THEN 1 ELSE 0 END AS M,
    CASE WHEN NAME = 'Yogurt' THEN 1 ELSE 0 END AS Y
FROM CART_PRODUCTS
    ) A
GROUP BY A.CART_ID 
HAVING SUM(A.M) >= 1
AND SUM(A.Y) >=1
;
