-- 코드를 입력하세요



SELECT 
    DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    A.PRODUCT_ID,
    A.USER_ID,
    A.SALES_AMOUNT
    
FROM ONLINE_SALE A
WHERE A.SALES_DATE LIKE '%2022-03%'

UNION ALL

SELECT 
    DATE_FORMAT(B.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    B.PRODUCT_ID,
    NULL AS USER_ID,
    B.SALES_AMOUNT
    
    
FROM OFFLINE_SALE B
WHERE B.SALES_DATE LIKE '%2022-03%'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID 
;


# SELECT 
#     SALES_DATE,
#     NULL AS USER_ID,
#     PRODUCT_ID,
#     SALES_AMOUNT,
#     SALES_DATE
    
# FROM OFFLINE_SALE 
# WHERE MONTH(SALES_DATE) = 3

# ;

# SELECT * 
# FROM OFFLINE_SALE;