-- 코드를 입력하세요

SELECT 
    A.CAR_ID,
    CASE WHEN COUNT (DISTINCT AVAILABILITY) = 2 THEN '대여중' 
    ELSE '대여 가능' END AS AVAILABILITY
FROM(
SELECT CAR_ID,
    CASE WHEN '2022-10-16' BETWEEN DATE(START_DATE) AND DATE(END_DATE) 
    OR DATE(END_DATE) = '2022-10-16' THEN '대여중' 
    ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) A
GROUP BY CAR_ID
ORDER BY CAR_ID DESC



