-- 코드를 입력하세요
# SELECT 
#     A.FLAVOR
#     # A.TOTAL_ORDER + B.TOTAL_ORDER AS TOJUL
# FROM FIRST_HALF A
#     JOIN JULY B
#     ON A.FLAVOR = B.FLAVOR
# # GROUP BY A.FLAVOR
# # ORDER BY TOJUL DESC
# ;


# SELECT 
#     B.FLAVOR,
#     SUM(TOTAL_ORDER) AS TOTAL_ORDER
# FROM FIRST_HALF B
# GROUP BY FLAVOR 
# ;

SELECT
    B.FLAVOR
    # B.FLAVOR,
    # B.TOTAL_ORDER + C.TOTAL_ORDER AS TOTAL
FROM(
SELECT 
    A.FLAVOR,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY A
GROUP BY FLAVOR 
    )B
    JOIN FIRST_HALF C
    ON B.FLAVOR = C.FLAVOR
GROUP BY B.FLAVOR
ORDER BY B.TOTAL_ORDER + C.TOTAL_ORDER DESC
LIMIT 3
;