-- 코드를 입력하세요


SELECT
    B.MONTH,
    B.CAR_ID,
    COUNT(*) AS RECORDS
FROM(
SELECT 
    MONTH(A.START_DATE) AS MONTH,
    A.car_id,
    count(*) OVER(PARTITION BY CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE MONTH(start_date) in (8, 9, 10)
) B
WHERE B.RECORDS >= 5
GROUP BY B.MONTH, B.CAR_ID
ORDER BY B.MONTH, B.CAR_ID DESC
;


