-- 코드를 입력하세요

SELECT
    # *
    B.INGREDIENT_TYPE,
    SUM(B.TOTAL_ORDER) AS TOTAL_ORDER
FROM(
SELECT 
    A.SHIPMENT_ID,
    A.FLAVOR,
    INGREDIENT_TYPE,
    A.TOTAL_ORDER
FROM FIRST_HALF A
LEFT JOIN ICECREAM_INFO ON
    A.FLAVOR = ICECREAM_INFO.FLAVOR
) B
GROUP BY INGREDIENT_TYPE
ORDER BY B.TOTAL_ORDER;